services:
  - type: web
    name: tmats-backend
    env: docker
    buildCommand: ./mvnw package -DskipTests
    startCommand: java -jar -Dspring.profiles.active=render target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: PORT
        value: 8080
      # The database environment variables are now set in the Render dashboard
      # These act as placeholders for documentation purposes
      # - key: PGHOST
      #   value: from-dashboard
      # - key: PGPORT
      #   value: from-dashboard  
      # - key: PGDATABASE
      #   value: from-dashboard
      # - key: PGUSER
      #   value: from-dashboard
      # - key: PGPASSWORD
      #   value: from-dashboard

# Removed the databases section as we're using an existing database 