services:
  - type: web
    name: tmats-backend
    env: docker
    buildCommand: ./mvnw package -DskipTests
    startCommand: java -jar -Dspring.profiles.active=render target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: PORT
        value: 8080

databases:
  - name: tmats-db
    databaseName: tmats
    user: tmats_user
    plan: free 